### DISCUSSION TITLE
Saving two checkpoints based on CER and WER

### DISCUSSION THREAD

**Discussion by solene-evain** [speechbrain/speechbrain#1747] [Q&A]
Hi everyone, 

I'm using speechbrain for ASR. I would need to save two checkpoints: one with the best CER and another with the best WER, but I'm not sure how to do so. 

Here is what I've got for now: 
`self.checkpointer.save_and_keep_only( #saves a checkpoint, then deletes the least important checkpoints
                meta={"CER": stage_stats["CER"], "WER": stage_stats["WER"]}, #a mapping which is added to the meta file in the checkpoint WER
                min_keys=["CER","WER"], #a list of keys for which the lowest value will be kept #WER
                num_to_keep=2,
            `)`

I'm not sure if the min_keys is just a list to say we want the first checkpoint to correspond to the best CER and the second one to correspond to the best WER, or if it says that two checkpoints will be saved, both with best CER and WER at the same time. 

Can someone enlighten me? 🙏🏻

Thanks!

**Comment by anautsch** [comment]
Hi @solene-evain please let me point you to the templates first—I write this to be better on the same page with you.

https://github.com/speechbrain/speechbrain/blob/develop/templates/speech_recognition/ASR/train.py
```python
...
    def compute_objectives(self, predictions, batch, stage):
        ...
        if stage != sb.Stage.TRAIN:
            ...
            self.wer_metric.append(batch.id, predicted_words, target_words)
            self.cer_metric.append(batch.id, predicted_words, target_words)
...
    def on_stage_start(self, stage, epoch):
        ...
        if stage != sb.Stage.TRAIN:
            self.cer_metric = self.hparams.cer_computer()
            self.wer_metric = self.hparams.error_rate_computer()
```
The whole output/logging procedure is specified here, that's where the checkpointing is done as well:
https://github.com/speechbrain/speechbrain/blob/3a90cf3fa20d4a9e80df4d0df3278b0d324d1b73/templates/speech_recognition/ASR/train.py#L246

```python
            self.checkpointer.save_and_keep_only(
                meta={"WER": stage_stats["WER"]}, min_keys=["WER"],
            )
```

The hparams `cer_computer` & `error_rate_computer` need to be defined (yaml lines 305+):
```yaml
# Functions that compute the statistics to track during the validation step.
error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True

# This object is used for saving the state of training both so that it
# can be resumed if it gets interrupted, and also so that the best checkpoint
# can be later loaded for evaluation or inference.
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        scheduler: !ref <lr_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>
```

From my understanding, checkpoints are chosen by learning rate; WER & CER are just metrics "for display". Let me check...
