### DISCUSSION TITLE
Using custom modules in a pretrained model

### DISCUSSION THREAD

**Discussion by courentin** [speechbrain/speechbrain#1835] [General]
We have built some custom modules on top of speechbrain (a tokenizer in particular) that we would like to use in a separate project (in a production environment).
We though about using the Pretrained interface, thus our hyperparams.yaml looks something like:

```yaml
modules:
  encoder: !ref <encoder>
  decoder: !ref <beam_searcher>
  normalizer: !ref <normalize>
tokenizer: !new:my_local_project.my_module.PhonemeTokenizer
  phoneme_to_token_path: !ref <tokenization[phoneme_to_token_path]>

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
  loadables: 
    model: !ref <model>
    normalizer: !ref <normalize>
```
With our custom module being:
```python
# in my_local_project/my_module.py
class PhonemeTokenizer(nn.Module):
    def __init__(self, phoneme_to_token_path: str) -> None:
        super().__init__()
        ...

    def decode_ids(self, token_sequence: List[int]) -> List[str]:
        ...
```

However, we can't use it in the other project as the `PhonemeTokenizer` is not present in it.

Would you have some ideas/best practices on how we can include those dependencies in our production environment without duplicating the `PhonemeTokenizer` code? (also, in the future, the `PhonemeTokenizer` may use external packages)
