### DISCUSSION TITLE
Can't load tokenizer for a tuned Whisper model

### DISCUSSION THREAD

**Discussion by rosyvs** [speechbrain/speechbrain#1946] [Q&A]
Hello,
I have tuned a Whisper model based on the recipe train_with_whisper.py in the Librispeech recipes.

It trained successfully and generated reasonable-looking output for the validation/test sets.

I am now trying to do inference using my model, so I am (attempting to) writing an inference script to load the model from its checkpoints.

From the tutorials (especially [this](https://colab.research.google.com/drive/1137MD-gAERblRAVhxDnwNXV3YyAiwtxV?usp=sharing#scrollTo=4RTi_EwOXzfb) one) I gather using the `WhisperASR.from_hparams()` method in `speechbrain.pretrained` should work well for my purposes. 
I've written an inference-only YAML based on my tuning YAML.
I have specified the following in my inference YAML:
```
model_type: tiny.en

...

whisper: !new:speechbrain.lobes.models.huggingface_whisper.HuggingFaceWhisper
    encoder_only: False
    source: !ref <model_src> # this is the local save dir containing ckpt
    save_path: !ref <cache_dir>
    # language: language
```

and have tried with and without specifying the tokenizer separately like this: 
```
# tokenizer: !new:transformers.models.whisper.tokenization_whisper.WhisperTokenizer
#     source: !ref openai/whisper-<model_type>
#     save_path: !ref <cache_dir>

...

modules:
    whisper: !ref <whisper>
    decoder: !ref <beam_searcher> # can change to greedy
    # tokenizer: !ref <tokenizer>

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    loadables:
        whisper: !ref <whisper>
        # tokenizer: !ref <tokenizer>
        decoder: !ref <decoder> 
    paths: 
        whisper: !ref <model_src>/whisper.ckpt
        # tokenizer: !ref openai/whisper-<model_type>
        decoder: !ref <model_src>/whisper.ckpt
```

I run into the error 

`OSError: Can't load tokenizer for '/Users/me/tuned_model_save_dir'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure  '/Users/me/tuned_model_save_dir' is the correct path to a directory containing all relevant files for a WhisperTokenizer tokenizer.`

I'm confused because I thought the tokenizer would have been saved inside the whisper.ckpt, as it seems to be an attribute of the HuggingFaceWhisper class rather than its own module.

I have tried specifying the huggingface hub as the source for the tokenizer, separately from the local path to my pretrained Whisper, but I get the same error. See the commented lines in my YAML snippet above for alternative paths I have tried.

**Has anyone had any success at all tuning their own Whisper and doing inference with it?
What method did you use? Perhaps I am barking up the wrong tree using the pretrainer! Thanks in advance for any thoughts on the matter!**
