### DISCUSSION TITLE
Speaker Identification Classifier Output Size

### DISCUSSION THREAD

**Discussion by amidstdebug** [speechbrain/speechbrain#2307] [Q&A]
Hi,

I was looking at the code for the speaker_id example, and saw that the output size of the classifier was 1211.

After doing some search, I found out that the `vox1` corpus has 1211 classes, but the corpus used: `mini-librispeech` only has 28.

Within `templates/speaker_id/train.yaml`, it states:
``` yaml

classifier: &id005 !new:custom_model.Classifier
  input_shape: [null, null, 512]
  activation: !name:torch.nn.LeakyReLU
  lin_blocks: 1
  lin_neurons: 512
  out_neurons: 28
```

Is the `custom_model` init for `templates/speaker_id/custom_model.py` wrong?

``` python
def __init__(
        self,
        input_shape,
        activation=torch.nn.LeakyReLU,
        lin_blocks=1,
        lin_neurons=512,
        out_neurons=1211, # is this supposed to be 1211 or 28?
    ):
```
