### DISCUSSION TITLE
Load a speechbrain-fine-tuned huggingface model checkpoint with the huggingface interface

### DISCUSSION THREAD

**Discussion by MaloMn** [speechbrain/speechbrain#2375] [Feature Request]
### 🚀 The feature

Currently, to achieve point (2), a `Pretrainer` object is necessary. 
1. Fine-tune a HuggingFace model and save checkpoint for resulting model
2. Use the fine-tuned model in a new recipe by loading it using the `HuggingFaceWav2Vec2` object.

It would be nice if the `HuggingFaceWav2Vec2` object could be used to load the fine-tuned model as well.

### Solution outline

To achieve this, a Pretrainer object is necessary (example below using a wav2vec2 model):
```yaml
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        wav2vec2: !ref <wav2vec2> # This corresponds the base wav2vec2 model used before fine-tuning
    paths:
        wav2vec2: path/to/fine-tuned/model/wav2vec2.ckpt
```

Along with it usage in the python recipe file once the brain (`asr_brain` here) has been instanciated.
```python
if "pretrainer" in hparams.keys():
        run_on_main(hparams["pretrainer"].collect_files)
        hparams["pretrainer"].load_collected(asr_brain.device)
```
