### DISCUSSION TITLE
Using a checkpoint from a model as a starting point for another model

### DISCUSSION THREAD

**Discussion by tshmak** [speechbrain/speechbrain#2646] [Q&A]
I'm trying to modify scripts from a [repo](https://github.com/Mu-Y/mpl-mdd) that uses (an old version of) speechbrain. Basically I can follow the repo and train a model, and checkpoints are saved in the folder `old_model/results/save/`. Now I want to use the (latest) checkpoint in `old_model/result/save` and finetune it on a new set of data and saving the results to a new `checkpoint_dir`. Let's call it `new_model/result/save`.

In the training script for the old model, I had: 
```
asr_brain = ASR(
    modules=hparams["modules"],
    hparams=hparams,
    run_opts=run_opts,
    checkpointer=hparams["checkpointer"],
)
```
where `ASR` subclasses `speechbrain.Brain`. 

In the `train.yaml` file (for the old model), I have: 
```
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        wav2vec2: !ref <wav2vec2>
        counter: !ref <epoch_counter>
```
where `save_folder` is `old_model/result/save`. 

Now I want to work in another folder (`new_model`) and save the new checkpoints to `new_model/result/save`. How do I rewrite the `train.yaml` to achieve what I want to do? 

Many thanks for your help. I've spent hours studying the tutorials and API docs to no avail.
