### DISCUSSION TITLE
How to preserve multilingual feature of ASR after fine-tuning?

### DISCUSSION THREAD

**Discussion by hforghani** [speechbrain/speechbrain#2777] [Q&A] [answered]
I fine-tuned Openai/whisper-large-v3 on my own dataset in Persian (fa) language. I used [the recipe `CommonVoice`](https://github.com/speechbrain/speechbrain/blob/develop/recipes/CommonVoice/ASR/transformer/train_with_whisper.py) but replaced my own Persian data. My data does not include any English word.

Here I tried to transcribe a voice file consisting some Persian and English words. I expect it to transcribe each one via its own language characters. The results is observed in the table below.

|  | Sentence |
| -- | -- |
| Reference | ادرس وب سایت اختصاصی جشنواره فیلم تروپفست عبارتست از www tropfest com |
| Hypothesis before fine-tuning | ادرس ویب سایت اختصاصی جشتواره فیلم تروپفست عبارت است از **www tropfest com** |
| Hypothesis after fine-tuning setting `language = fa` | ادرس وب سایت اختصاصی جشنواره فیلم تروپ فست عبارت است از **دبلیو دبلیو دبلیو دات تراپ فست دات کام** |
| Hypothesis after fine-tuning setting `language = null` | ادرس وب سایت اختصاصی جشنواره فیلم تروپ فست عبارت است از **دبلیو دبلیو دبلیو دات تروپ فست دات کام** |

The first row of the table shows the reference sentence. The second is the result of whisper-large-v3 before fine-tuning. You can observe it correctly transcribed `www tropfest com`. The third row is after fine-tuning setting `language = fa` in `hyperparams.yaml` file:

```yaml
language: fa

...

whisper: !new:speechbrain.lobes.models.huggingface_transformers.whisper.Whisper
  source: !ref <whisper_hub>
  freeze: !ref <freeze_whisper>
  freeze_encoder: !ref <freeze_encoder>
  save_path: !ref /home/dev/workspace/huggingface_cache/hub
  language: !ref <language>
  task: "transcribe"
```

We observe it transcribed it using some Persian characters: `دبلیو دبلیو دبلیو دات تراپ فست دات کام` which is not desird. In order to fix this behavior I changed the code a little. First I set `language = null` in `hyperparams.yaml` file:
```yaml
language: null

...

whisper: !new:speechbrain.lobes.models.huggingface_transformers.whisper.Whisper
  source: !ref <whisper_hub>
  freeze: !ref <freeze_whisper>
  freeze_encoder: !ref <freeze_encoder>
  save_path: !ref /home/dev/workspace/huggingface_cache/hub
  language: !ref <language>
  task: "transcribe"
```
Then I commented these lines in the class Whisper in `speechbrain.lobes.models.huggingface_transformers.whisper` module:

```python
class Whisper(HFTransformersInterface):
    ...
    @torch.no_grad()
    def detect_language(self, mel):
        # if self.tokenizer.language is None:
        #     raise ValueError(
        #         "This model doesn't have language tokens so it can't perform lang id"
        #     )
        ...
```
in order not to raise error when tokenizer language is `None`. The fourth row corresponds to the result. It still is not desired!

What is the solution to preserve multilingual transcription of ASR while fine-tuning? Is it due to incorrect language setting? Or I am forced to provide multilingual data?
