### ISSUE TITLE
Speaker ID from Scratch: Problems with sample rate

### ISSUE THREAD

**Issue by karla3jo** [speechbrain/speechbrain#1150]
Hi, 

I'm trying to fit my custom dataset following the tutorial from https://colab.research.google.com/drive/1UwisnAjr8nQF3UnrkIJ4abBMAWzVwBMh?usp=sharing. 

I don't need the environment corruption nor the augmentation features, so I basically commented them. I see the sample rate constant of 16000 apparently is only affecting the augmentation process, so I'm guessing it should not affect if my dataset doesn't have this sample rate. Am I correct or am I missing something? Since I'm getting an awful testing error at the end...

Also, I have noticed in the documentation that EncoderClassifier says "Make sure the sample rate is fs=16000 Hz.", so now I'm wondering if this will later disturb the inference phase when my audios are not set at this sample rate. Do I have to convert them to 16kHz to keep going?

Thanks in advance for your attention.

**Comment by mravanelli** [comment]
Hi @karla3jo, what is the sampling rate of the signals in your dataset?

**Comment by karla3jo** [comment]
The sampling rates of my signals are 44 or 48kHz. I've managed to resample all signals to 16KHz with torchaudio.transforms.Resample at audio_pipeline in train.py: It performs slightly better than before but, still, there is a high test error. I'm attaching the train_log file.
[train_log.txt](https://github.com/speechbrain/speechbrain/files/7604442/train_log.txt)

I have augmented the custom dataset by overlaying different background noises and transforming the original audios at higher and lower speeds --that's the reason I've removed the augmentation process from the yaml file, because I already do it myself. Perhaps my dataset is still not big enough and it's overfitting?

Also tried to obtain more feature parameters from the audios (the tutorial only takes n_mels) like in https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/hparams/train_ecapa_tdnn.yaml#L158, preserving the LinearScheduler and dismissing the augmentation pipeline. However, is more or less the same...

[train_efeats.log](https://github.com/speechbrain/speechbrain/files/7604507/train_efeats.log)

**Comment by mravanelli** [comment]
How big is your dataset and how many speakers do you have?  If the dataset is not very big, my suggestion is to pretrain the embedding model with the one we shared for voxceleb. You can see how you can pretrain a model from [this example](https://github.com/speechbrain/speechbrain/blob/develop/recipes/VoxCeleb/SpeakerRec/hparams/verification_ecapa.yaml#L77).

**Comment by karla3jo** [comment]
My training dataset has 4795 audios with lengths ranging from 3 to 16 seconds of 38 speakers. However, the quantity of audios per speaker differ from each other: the speaker with less audios has 21 training audios, while there are speakers with +300 training audios. I will run the experiment again with a pretrain of the embedding model as you suggested, my yaml file looks like this:
```
# #################################
# Basic training parameters for speaker-id. We have first a network that
# computes some embeddings. On the top of that, we employ a classifier.
#
# Author:
#  * Mirco Ravanelli 2021
# #################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# If you plan to train a system on an HPC cluster with a big dataset,
# we strongly suggest doing the following:
# 1- Compress the dataset in a single tar or zip file.
# 2- Copy your dataset locally (i.e., the local disk of the computing node).
# 3- Uncompress the dataset in the local folder.
# 4- Set data_folder with the local path.
# Reading data from the local disk of the compute node (e.g. $SLURM_TMPDIR with SLURM-based clusters) is very important.
# It allows you to read the data much faster without slowing down the shared filesystem.
data_folder: /home/user/data
output_folder: !ref /home/user/results/speaker_id/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt
pretrain_path: speechbrain/spkrec-ecapa-voxceleb

# Path where data manifest files will be stored
# The data manifest files are created by the data preparation script.
train_annotation: train.json
valid_annotation: valid.json
test_annotation: test.json

# The train logger writes training statistics to a file, as well as stdout.
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

ckpt_interval_minutes: 15 # save checkpoint every N min

# Feature parameters
n_mels: 23

# Training Parameters
sample_rate: 16000
number_of_epochs: 35
batch_size: 8 #16
lr_start: 0.001
lr_final: 0.0001
n_classes: 38 # In this case, we have 28 speakers
emb_dim: 512 # dimensionality of the embeddings
dataloader_options:
    batch_size: !ref <batch_size>


# Added noise and reverb come from OpenRIR dataset, automatically
# downloaded and prepared with this Environmental Corruption class.
# env_corrupt: !new:speechbrain.lobes.augment.EnvCorrupt
#     openrir_folder: !ref <data_folder>
#     babble_prob: 0.0
#     reverb_prob: 0.0
#     noise_prob: 1.0
#     noise_snr_low: 0
#     noise_snr_high: 15

# Adds speech change + time and frequency dropouts (time-domain implementation)
# # A small speed change help to improve the performance of speaker-id as well.
# augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
#     sample_rate: !ref <sample_rate>
#     speeds: [95, 100, 105]

# Feature extraction
compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

# Mean and std normalization of the input features
mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

# To design a custom model, either just edit the simple CustomModel
# class that's listed here, or replace this `!new` call with a line
# pointing to a different file you've defined.
embedding_model: !new:custom_model.Xvector
    in_channels: !ref <n_mels>
    activation: !name:torch.nn.LeakyReLU
    tdnn_blocks: 5
    tdnn_channels: [512, 512, 512, 512, 1500]
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    lin_neurons: !ref <emb_dim>

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        embedding_model: !ref <embedding_model>
    paths:
        embedding_model: !ref <pretrain_path>/embedding_model.ckpt

classifier: !new:custom_model.Classifier
    input_shape: [null, null, !ref <emb_dim>]
    activation: !name:torch.nn.LeakyReLU
    lin_blocks: 1
    lin_neurons: !ref <emb_dim>
    out_neurons: !ref <n_classes>

# The first object passed to the Brain class is this "Epoch Counter"
# which is saved by the Checkpointer so that training can be resumed
# if it gets interrupted at any point.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

# Objects in "modules" dict will have their parameters moved to the correct
# device, as well as having train()/eval() called on them by the Brain class.
modules:
    compute_features: !ref <compute_features>
    #env_corrupt: !ref <env_corrupt>
    #augmentation: !ref <augmentation>
    embedding_model: !ref <embedding_model>
    classifier: !ref <classifier>
    mean_var_norm: !ref <mean_var_norm>

# This optimizer will be constructed by the Brain class after all parameters
# are moved to the correct device. Then it will be added to the checkpointer.
opt_class: !name:torch.optim.Adam
    lr: !ref <lr_start>

# This function manages learning rate annealing over the epochs.
# We here use the simple lr annealing method that linearly decreases
# the lr from the initial value to the final one.
lr_annealing: !new:speechbrain.nnet.schedulers.LinearScheduler
    initial_value: !ref <lr_start>
    final_value: !ref <lr_final>
    epoch_count: !ref <number_of_epochs>

# This object is used for saving the state of training both so that it
# can be resumed if it gets interrupted, and also so that the best checkpoint
# can be later loaded for evaluation or inference.
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        embedding_model: !ref <embedding_model>
        classifier: !ref <classifier>
        normalizer: !ref <mean_var_norm>
        counter: !ref <epoch_counter>
```
