### ISSUE TITLE
How to train without environment corruption and augmentation? SPEAKER ID TRAINING

### ISSUE THREAD

**Issue by saumyaborwankar** [speechbrain/speechbrain#1193]
I have been following the ipynb notebook given for speaker ID training (speaker verification). In the train.yaml file there are 2 things "env_corrupt" and "augmentation". I dont want to use these 2, how should I remove them from the yaml file? I tried commenting them from the yaml file but it causes an error. Any advice would be helpful. Thanks.

**Comment by Gastron** [comment]
Are you talking about this error: https://github.com/speechbrain/speechbrain/issues/1150#issuecomment-993433882 ?

In that case, looks like you still have a reference to env_corrupt in the YAML that hasn't been commented. Search for env_corrupt or augmentation (could be under the modules: block for example) and comment those as well. On the Python side you should make sure that augmentation is also skipped/commented out, though many SpeechBrain training scripts already skip augmentation if the attribute is not found in hparams.

**Comment by saumyaborwankar** [comment]
Okay thanks understood. Sorry for such a noob question

**Comment by saumyaborwankar** [comment]
So when I trained the data without changing the yaml file the training ended. But after i commented "env_corrupt" and "augmentation" I ran into this error while in first epoch.
```

Traceback (most recent call last):
  File "03_saumya_train.py", line 324, in <module>
    valid_loader_kwargs=hparams["dataloader_options"],
  File "/home/pankaj/anaconda3/envs/saumya/lib/python3.7/site-packages/speechbrain/core.py", line 1033, in fit
    loss = self.fit_batch(batch)
  File "/home/pankaj/anaconda3/envs/saumya/lib/python3.7/site-packages/speechbrain/core.py", line 853, in fit_batch
    outputs = self.compute_forward(batch, Stage.TRAIN)
  File "03_saumya_train.py", line 60, in compute_forward
    predictions = self.modules.classifier(embeddings)
  File "/home/pankaj/anaconda3/envs/saumya/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pankaj/anaconda3/envs/saumya/lib/python3.7/site-packages/speechbrain/nnet/containers.py", line 144, in forward
    x = layer(x)
  File "/home/pankaj/anaconda3/envs/saumya/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pankaj/anaconda3/envs/saumya/lib/python3.7/site-packages/speechbrain/nnet/normalization.py", line 91, in forward
    x_n = self.norm(x)
  File "/home/pankaj/anaconda3/envs/saumya/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pankaj/anaconda3/envs/saumya/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 179, in forward
    self.eps,
  File "/home/pankaj/anaconda3/envs/saumya/lib/python3.7/site-packages/torch/nn/functional.py", line 2280, in batch_norm
    _verify_batch_size(input.size())
  File "/home/pankaj/anaconda3/envs/saumya/lib/python3.7/site-packages/torch/nn/functional.py", line 2248, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512, 1])
```

Any idea what might be wrong?

**Comment by saumyaborwankar** [comment]
Hey @Gastron the batch size was 16 when this error occurred. I'll attach my train.yaml file here for reference. 

```
# Basic training parameters for speaker-id. We have first a network that
# computes some embeddings. On the top of that, we employ a classifier.
#
# Author:
#  * Mirco Ravanelli 2021
# #################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]

# If you plan to train a system on an HPC cluster with a big dataset,
# we strongly suggest doing the following:
# 1- Compress the dataset in a single tar or zip file.
# 2- Copy your dataset locally (i.e., the local disk of the computing node).
# 3- Uncompress the dataset in the local folder.
# 4- Set data_folder with the local path.
# Reading data from the local disk of the compute node (e.g. $SLURM_TMPDIR with SLURM-based clusters) is very important.
# It allows you to read the data much faster without slowing down the shared filesystem.
data_folder: ./saumya_data
output_folder: !ref ./results/speaker_id/<seed>
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Path where data manifest files will be stored
# The data manifest files are created by the data preparation script.
train_annotation: train.json
valid_annotation: valid.json
test_annotation: test.json

# The train logger writes training statistics to a file, as well as stdout.
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.classification_error
        reduction: batch

ckpt_interval_minutes: 15 # save checkpoint every N min

# Feature parameters
n_mels: 23

# Training Parameters
sample_rate: 16000
number_of_epochs: 35
batch_size: 16
lr_start: 0.001
lr_final: 0.0001
n_classes: 5 # In this case, we have 28 speakers
emb_dim: 512 # dimensionality of the embeddings
dataloader_options:
    batch_size: !ref <batch_size>


# Added noise and reverb come from OpenRIR dataset, automatically
# downloaded and prepared with this Environmental Corruption class.
# env_corrupt: !new:speechbrain.lobes.augment.EnvCorrupt
#     openrir_folder: !ref <data_folder>
#     babble_prob: 0.0
#     reverb_prob: 0.0
#     noise_prob: 1.0
#     noise_snr_low: 0
#     noise_snr_high: 15

# Adds speech change + time and frequency dropouts (time-domain implementation)
# A small speed change help to improve the performance of speaker-id as well.
# augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
#     sample_rate: !ref <sample_rate>
#     speeds: [95, 100, 105]

# Feature extraction
compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

# Mean and std normalization of the input features
mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

# To design a custom model, either just edit the simple CustomModel
# class that's listed here, or replace this `!new` call with a line
# pointing to a different file you've defined.
embedding_model: !new:custom_model.Xvector
    in_channels: !ref <n_mels>
    activation: !name:torch.nn.LeakyReLU
    tdnn_blocks: 5
    tdnn_channels: [512, 512, 512, 512, 1500]
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    lin_neurons: !ref <emb_dim>

classifier: !new:custom_model.Classifier
    input_shape: [null, null, !ref <emb_dim>]
    activation: !name:torch.nn.LeakyReLU
    lin_blocks: 1
    lin_neurons: !ref <emb_dim>
    out_neurons: !ref <n_classes>

# The first object passed to the Brain class is this "Epoch Counter"
# which is saved by the Checkpointer so that training can be resumed
# if it gets interrupted at any point.
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

# Objects in "modules" dict will have their parameters moved to the correct
# device, as well as having train()/eval() called on them by the Brain class.
modules:
    compute_features: !ref <compute_features>
    # env_corrupt: !ref <env_corrupt>
    # augmentation: !ref <augmentation>
    embedding_model: !ref <embedding_model>
    classifier: !ref <classifier>
    mean_var_norm: !ref <mean_var_norm>

# This optimizer will be constructed by the Brain class after all parameters
# are moved to the correct device. Then it will be added to the checkpointer.
opt_class: !name:torch.optim.Adam
    lr: !ref <lr_start>

# This function manages learning rate annealing over the epochs.
# We here use the simple lr annealing method that linearly decreases
# the lr from the initial value to the final one.
lr_annealing: !new:speechbrain.nnet.schedulers.LinearScheduler
    initial_value: !ref <lr_start>
    final_value: !ref <lr_final>
    epoch_count: !ref <number_of_epochs>

# This object is used for saving the state of training both so that it
# can be resumed if it gets interrupted, and also so that the best checkpoint
# can be later loaded for evaluation or inference.
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        embedding_model: !ref <embedding_model>
        classifier: !ref <classifier>
        normalizer: !ref <mean_var_norm>
        counter: !ref <epoch_counter>

```
