### ISSUE TITLE
ASR Inference

### ISSUE THREAD

**Issue by nairaxo** [speechbrain/speechbrain#1280]
Hello!
I'm facing this error when performing ASR inference with local model. I followed this proposed [solution](https://github.com/speechbrain/speechbrain/issues/1061#issuecomment-950741481) but i guess that my ****.model is not recognized. 

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/n.abdoumohamed/DVoice/speechbrain/speechbrain/pretrained/interfaces.py", line 360, in from_hparams
    pretrainer.load_collected(device="cpu")
  File "/home/n.abdoumohamed/DVoice/speechbrain/speechbrain/utils/parameter_transfer.py", line 203, in load_collected
    self._call_load_hooks(paramfiles, device)
  File "/home/n.abdoumohamed/DVoice/speechbrain/speechbrain/utils/parameter_transfer.py", line 230, in _call_load_hooks
    raise RuntimeError(MSG)
RuntimeError: Don't know how to load <class 'str'>. Register default hook                     or add custom hook for this object.
`

**Comment by Gastron** [comment]
The error says your model is just a string. My guess: you need to add !ref < > around your model in YAML. Basically, the Pretrainer does not get a reference to your model instance, it's getting a string instead.

**Comment by nairaxo** [comment]
Thank you for your response. I fixed the problem. It was indeed because of !ref. However, I am facing another error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/n.abdoumohamed/DVoice/speechbrain/speechbrain/pretrained/interfaces.py", line 525, in transcribe_file
    predicted_words, predicted_tokens = self.transcribe_batch(
  File "/home/n.abdoumohamed/DVoice/speechbrain/speechbrain/pretrained/interfaces.py", line 590, in transcribe_batch
    predicted_words = [
  File "/home/n.abdoumohamed/DVoice/speechbrain/speechbrain/pretrained/interfaces.py", line 591, in <listcomp>
    self.tokenizer.decode_ids(token_seq)
AttributeError: 'str' object has no attribute 'decode_ids'
`

I think it is due to maybe a bad configuration of the decoder. Here is my yaml file. I can't see what I might have missed... 


````
# ############################################################################
# Model: E2E ASR with attention-based ASR
# Encoder: CRDNN model
# Decoder: GRU + beamsearch + RNNLM
# Tokens: BPE with unigram
# Authors:  Ju-Chieh Chou, Mirco Ravanelli, Abdel Heba, Peter Plantinga 2020
# ############################################################################


# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 256)
inter_layer_pooling_size: (2, 2)
cnn_kernelsize: (3, 3)
time_pooling_size: 4
rnn_class: !name:speechbrain.nnet.RNN.LSTM
rnn_layers: 4
rnn_neurons: 1024
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 512
emb_size: 128
dec_neurons: 1024
output_neurons: 68  # index(blank/eos/bos) = 0
blank_index: 0

# Decoding parameters
bos_index: 0
eos_index: 0
min_decode_ratio: 0.0
max_decode_ratio: 1.0
beam_size: 80
eos_threshold: 1.5
using_max_attn_shift: True
max_attn_shift: 240
lm_weight: 0.50
coverage_penalty: 1.5
temperature: 1.25
temperature_lm: 1.25

normalize: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>

enc: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_shape: [null, null, !ref <n_mels>]
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    inter_layer_pooling_size: !ref <inter_layer_pooling_size>
    time_pooling: True
    using_2d_pooling: False
    time_pooling_size: !ref <time_pooling_size>
    rnn_class: !ref <rnn_class>
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    rnn_re_init: True
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

emb: !new:speechbrain.nnet.embedding.Embedding
    num_embeddings: !ref <output_neurons>
    embedding_dim: !ref <emb_size>

dec: !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
    enc_dim: !ref <dnn_neurons>
    input_size: !ref <emb_size>
    rnn_type: gru
    attn_type: location
    hidden_size: !ref <dec_neurons>
    attn_dim: 1024
    num_layers: 1
    scaling: 1.0
    channels: 10
    kernel_size: 100
    re_init: True
    dropout: !ref <dropout>

ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>

seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dec_neurons>
    n_neurons: !ref <output_neurons>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

lm_model: !new:speechbrain.lobes.models.RNNLM.RNNLM
    output_neurons: !ref <output_neurons>
    embedding_dim: !ref <emb_size>
    activation: !name:torch.nn.LeakyReLU
    dropout: 0.0
    rnn_layers: 2
    rnn_neurons: 2048
    dnn_blocks: 1
    dnn_neurons: 512
    return_hidden: True  # For inference

#tokenizer: !new:sentencepiece.SentencePieceProcessor

tokenizer: /home/n.abdoumohamed/DVoice/jobs/results/wav2vec2_ctc_dar/1234/save/68_char.vocab

#tokenizer: !ref <tokenizer_model>


#asr_model: !new:torch.nn.ModuleList
#    - [!ref <enc>, !ref <emb>, !ref <dec>, !ref <ctc_lin>, !ref <seq_lin>]
asr_model: /home/n.abdoumohamed/DVoice/jobs/results/wav2vec2_ctc_dar/1234/save/ckpt2/asr.ckpt
# We compose the inference (encoder) pipeline.
encoder: !new:speechbrain.nnet.containers.LengthsCapableSequential
    input_shape: [null, null, !ref <n_mels>]
    compute_features: !ref <compute_features>
    normalize: !ref <normalize>
    model: !ref <enc>

decoder: !new:speechbrain.decoders.S2SRNNBeamSearchLM
    embedding: !ref <emb>
    decoder: !ref <dec>
    linear: !ref <seq_lin>
    language_model: !ref <lm_model>
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <beam_size>
    eos_threshold: !ref <eos_threshold>
    using_max_attn_shift: !ref <using_max_attn_shift>
    max_attn_shift: !ref <max_attn_shift>
    coverage_penalty: !ref <coverage_penalty>
    lm_weight: !ref <lm_weight>
    temperature: !ref <temperature>
    temperature_lm: !ref <temperature_lm>


modules:
    encoder: !ref <encoder>
    decoder: !ref <decoder>
    #lm_model: !ref <lm_model>

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    paths:
        asr: !ref <asr_model>
        lm: !ref <lm_model>
        tokenizer: !ref <tokenizer>
````
