### ISSUE TITLE
TIMIT model pretrained recipe

### ISSUE THREAD

**Issue by kalvinchang** [speechbrain/speechbrain#1444]
I am trying to load the pretrained TIMIT recipe that achieved 8.04% PER on the benchmark. 

However,

**Comment by kalvinchang** [comment]
Here is the YAML file in question

```
# Generated 2021-04-10 from:
# /network/tmp1/ravanelm/speechbrain_github/speechbrain_wav2vect/recipes/TIMIT/ASR/seq2seq/hparams/train_with_wav2vec2.yaml
# yamllint disable
# ################################
# Model: seq2seq ASR on TIMIT with wav2vec2 + CTC/Attention
# Authors:
# * Titouan Parcollet 2021
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [1234]
output_folder: results/augment_noise_CRDNN/1234
wer_file: results/augment_noise_CRDNN/1234/wer.txt
save_folder: results/augment_noise_CRDNN/1234/save
train_log: results/augment_noise_CRDNN/1234/train_log.txt

# URL for the biggest Fairseq english wav2vec2 model.
wav2vec2_hub: facebook/wav2vec2-large-lv60

# Data files
data_folder: /localscratch/TIMIT
                           # e.g. /path/to/TIMIT
train_annotation: results/augment_noise_CRDNN/1234/train.json
valid_annotation: results/augment_noise_CRDNN/1234/dev.json
test_annotation: results/augment_noise_CRDNN/1234/test.json
skip_prep: false # Skip data preparation

# Training parameters
number_of_epochs: 20
batch_size: 8
lr: 0.0003
lr_wav2vec: 0.0001
ctc_weight: 0.2
sorting: ascending
auto_mix_prec: false
sample_rate: 16000

# Model parameters
activation: &id001 !name:torch.nn.LeakyReLU
dnn_layers: 2
dnn_neurons: 1024
emb_size: 128
dec_neurons: 256
freeze_wav2vec: false

# Outputs
output_neurons: 42 # 39phs+blank+eos+bos
bos_index: 0
eos_index: 1
blank_index: 2

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 1.0
beam_size: 16
eos_threshold: 1.5

# Dataloader options
train_dataloader_opts:
  batch_size: 8
  num_workers: 8

valid_dataloader_opts:
  batch_size: 8
  num_workers: 8

test_dataloader_opts:
  batch_size: 8
  num_workers: 8

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
  sample_rate: 16000
  speeds: [95, 100, 105]

epoch_counter: &id011 !new:speechbrain.utils.epoch_loop.EpochCounter

  limit: 20

enc: &id006 !new:speechbrain.lobes.models.VanillaNN.VanillaNN
  input_shape: [null, null, 1024]
  activation: *id001
  dnn_blocks: 2
  dnn_neurons: 1024

wav2vec2: &id007 !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
  source: facebook/wav2vec2-large-lv60
  output_norm: true
  freeze: false
  save_path: results/augment_noise_CRDNN/1234/save/wav2vec2_checkpoint

#####
# Uncomment this block if you prefer to use a Fairseq pretrained model instead
# of a HuggingFace one. Here, we provide an URL that is obtained from the
# Fairseq github for an equivalent model compared to HuggingFace.
#
#wav2vec2_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_new.pt
#wav2vec2: !new:speechbrain.lobes.models.fairseq_wav2vec.FairseqWav2Vec2
#    pretrained_path: !ref <wav2vec2_url>
#    output_norm: True
#    freeze: False
#    save_path: !ref <save_folder>/wav2vec2_checkpoint/model.pt
#####

emb: &id002 !new:speechbrain.nnet.embedding.Embedding
  num_embeddings: 42
  embedding_dim: 128

dec: &id003 !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
  enc_dim: 1024
  input_size: 128
  rnn_type: gru
  attn_type: location
  hidden_size: 256
  attn_dim: 256
  num_layers: 1
  scaling: 1.0
  channels: 10
  kernel_size: 100
  re_init: true
  dropout: 0.5

ctc_lin: &id005 !new:speechbrain.nnet.linear.Linear
  input_size: 1024
  n_neurons: 42                       # 39 phonemes + 1 blank

seq_lin: &id004 !new:speechbrain.nnet.linear.Linear

  input_size: 256
  n_neurons: 42                       # 39 phonemes + 1 eos

log_softmax: !new:speechbrain.nnet.activations.Softmax
  apply_log: true

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
  blank_index: 2

seq_cost: !name:speechbrain.nnet.losses.nll_loss
  label_smoothing: 0.1

greedy_searcher: !new:speechbrain.decoders.seq2seq.S2SRNNGreedySearcher
  embedding: *id002
  decoder: *id003
  linear: *id004
  bos_index: 0
  eos_index: 1
  min_decode_ratio: 0.0
  max_decode_ratio: 1.0

beam_searcher: !new:speechbrain.decoders.seq2seq.S2SRNNBeamSearcher
  embedding: *id002
  decoder: *id003
  linear: *id004
  ctc_linear: *id005
  bos_index: 0
  eos_index: 1
  blank_index: 2
  min_decode_ratio: 0.0
  max_decode_ratio: 1.0
  beam_size: 16

model: &id008 !new:torch.nn.ModuleList
- [*id006, *id002, *id003, *id005, *id004]
adam_opt_class: !name:torch.optim.Adam
  lr: 0.0003

wav2vec_opt_class: !name:torch.optim.Adam
  lr: 0.0001

lr_annealing_adam: &id009 !new:speechbrain.nnet.schedulers.NewBobScheduler
  initial_value: 0.0003
  improvement_threshold: 0.0025
  annealing_factor: 0.8
  patient: 0

lr_annealing_wav2vec: &id010 !new:speechbrain.nnet.schedulers.NewBobScheduler
  initial_value: 0.0001
  improvement_threshold: 0.0025
  annealing_factor: 0.9

modules:
  wav2vec2: *id007
  enc: *id006
  emb: *id002
  dec: *id003
  ctc_lin: *id005
  seq_lin: *id004
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: results/augment_noise_CRDNN/1234/save
  recoverables:
    model: *id008
    wav2vec2: *id007
    lr_annealing_adam: *id009
    lr_annealing_wav2vec: *id010
    counter: *id011
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: results/augment_noise_CRDNN/1234/train_log.txt

ctc_stats: !name:speechbrain.utils.metric_stats.MetricStats
  metric: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: 2
    reduction: batch

seq_stats: !name:speechbrain.utils.metric_stats.MetricStats
  metric: !name:speechbrain.nnet.losses.nll_loss
    label_smoothing: 0.1
    reduction: batch

per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
  loadables:
    asr: !ref <model>
  paths:
    asr: !ref <checkpointer.checkpoints_dir>/model.ckpt
```
