### ISSUE TITLE
MetricGAN+ checkpoint out of date

### ISSUE THREAD

**Issue by boyima-nureva** [speechbrain/speechbrain#1482]
Hello,

I think the checkpoints uploaded to https://drive.google.com/drive/folders/1kQdfTr6yA_tGDxeadQQrR42SmOOkidRz is now out of date and no longer compatible with the current MetricGAN+ recipe. 

Under `hyperparams.yaml`, the recoverables are now 
```
recoverables:
    generator: *id001
    discriminator: *id002
    counter: *id003
```
while in the Google Driver folder, there is only a checkpoint for `model`, but not generator and discriminator.

Would it be possible for you to upload a new version of the model?
