### ISSUE TITLE
Load pre-trained models

### ISSUE THREAD

**Issue by aheba** [speechbrain/speechbrain#163]
Hey @mravanelli @pplantinga @Gastron @TParcollet ,

With my transducer, I'm thinking about adding specific pre-trained option to handle the load of pre-trained models from CTC for example..

The first solution is to add an option in checkpointer like this:
```
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        encoder_crdnn: !ref <encoder_crdnn>
        encoder_lin: !ref <encoder_lin>
        decoder_gru: !ref <decoder_gru>
        decoder_lin: !ref <decoder_lin>
        joint_lin: !ref <joint_lin>
        output: !ref <output>
        optimizer: !ref <optimizer>
        scheduler: !ref <lr_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>
```
And consider that encoder_crdnn and encoder_lin have same dim as CTC recipe..I'm thinking about creating an option like:
```
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    pre-trained-dir: !ref <pretrained_folder>
    load-pre-trained:
        encoder_crdnn: !ref <encoder_crdnn>
        encoder_lin: !ref <encoder_lin>
    recoverables:
        encoder_crdnn: !ref <encoder_crdnn>
        encoder_lin: !ref <encoder_lin>
        decoder_gru: !ref <decoder_gru>
        decoder_lin: !ref <decoder_lin>
        joint_lin: !ref <joint_lin>
        output: !ref <output>
        optimizer: !ref <optimizer>
        scheduler: !ref <lr_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>
```

Or adding a class as @TParcollet  propose to load model at the begning..
