### ISSUE TITLE
[Bug]: Inference got stuck without any error

### ISSUE THREAD

**Issue by GryffindorLi** [speechbrain/speechbrain#1773]
### Describe the bug

Hi,

I am training a Conformer-RNN-T model with `attention_type='RelPosMHAXL'` on CommonVoice French dataset. 

During the validation step of the training iterations, sometimes it gets stuck in one batch, without any error. It just stuck with no further progress.

### To Reproduce

Here are some configurations that related to my beam searcher.

```yaml
batch_size_valid: 16

beam_size: 4
nbest: 1
# by default {state,expand}_beam = 2.3 as mention in paper
# https://arxiv.org/abs/1904.02619
state_beam: 2.3
expand_beam: 2.3

beam_searcher: !new:speechbrain.decoders.transducer.TransducerBeamSearcher
   decode_network_lst: [!ref <emb>, !ref <dec>]
   tjoint: !ref <Tjoint>
   classifier_network: [!ref <transducer_lin>]
   blank_id: !ref <blank_index>
   beam_size: !ref <beam_size>
   nbest: !ref <nbest>
   state_beam: !ref <state_beam>
   expand_beam: !ref <expand_beam>

```

### Versions

My python version is 3.8.8 and the SpeechBrain version is `0.5.13`, and my pytorch version is
![image](https://user-images.githubusercontent.com/40144709/209164410-0c8f393a-2550-4376-bc0e-ac45439e77e4.png).

### Relevant log output

There is no log output at all, it just stuck. 

I am training the model on a SLURM-based cluster, so I can see that the SLURM's out file is not update for a very long time. My hardware is:

```
#SBATCH --nodes=1

#SBATCH --ntasks-per-node=1

#SBATCH --cpus-per-task=4

#SBATCH --mem-per-cpu=4GB

# Request a GPU
#SBATCH --gres=gpu:a40:1
```
