### ISSUE TITLE
[Bug]: Speaker Classification Inference KeyError

### ISSUE THREAD

**Issue by praveenmathew93** [speechbrain/speechbrain#1795]
### Issue
This is similar to the #1049 issue, the only difference being that it was for language identification.

I trained a model using some audio from commonvoice. The model completed training. I am doing inference now.

This is my Inference code:

```python
from speechbrain.pretrained import EncoderClassifier
import os
import sys
import torch
import torchaudio

classifier = EncoderClassifier.from_hparams(source="./content/best_model/", hparams_file='hparams_inference.yaml', savedir="./content/best_model/")

# Classification
audio_file = 'data/common_voice_de_27022043.wav'
signal, fs = torchaudio.load(audio_file) # test_speaker: 5789
output_probs, score, index, text_lab = classifier.classify_batch(signal)
print('Target: 000fc181c938978e23ec7c066dddc246ca2b3160b50e3bfee829c02f5db753b3b8b955ad0f1b3effc954e5b10b474e6e93386f2b7925e7195abd84a164477851, Predicted: ' + text_lab[0])

# Speaker 2
audio_file = 'data/common_voice_de_18351596.wav'
signal, fs =torchaudio.load(audio_file) # test_speaker: 460
output_probs, score, index, text_lab = classifier.classify_batch(signal)
print('Target: 0e156ff8b3bdd99355fd7f99e2259c47bb78e7dcac346a9966181b9e5e265960ddccc5f73b036948d3586a03e8b482b01d908da93026737ac60a9996d88d6881, Predicted: ' + text_lab[0])
```

I get the error KeyError: 0

I have added the pre-trainer link in the YAML. This is what that part looks like:
```yaml
modules:
    compute_features: !ref <compute_features>
    embedding_model: !ref <embedding_model>
    classifier: !ref <classifier>
    mean_var_norm: !ref <mean_var_norm>

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    loadables:
        embedding_model: !ref <embedding_model>
        classifier: !ref <classifier>
        label_encoder: !ref <label_encoder>
    paths:
        embedding_model: !ref <pretrained_path>/embedding_model.ckpt
        classifier: !ref <pretrained_path>/classifier.ckpt
        label_encoder: !ref <pretrained_path>/label_encoder.txt`

##I have attached my label encoder in the comments
```

Could you tell me what I am missing here? 

### Expected behaviour

Successful Inference 

### To Reproduce

Compete YAML file below:
# #################################

```yaml
# pretrain folders:
pretrained_path: /content/best_model/


# Model parameters
n_mels: 23
sample_rate: 16000
n_classes: 29 # In this case, we have 28 speakers
emb_dim: 512 # dimensionality of the embeddings

# Feature extraction
compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

# Mean and std normalization of the input features
mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False


embedding_model: !new:custom_model.Xvector
    in_channels: !ref <n_mels>
    activation: !name:torch.nn.LeakyReLU
    tdnn_blocks: 5
    tdnn_channels: [512, 512, 512, 512, 1500]
    tdnn_kernel_sizes: [5, 3, 3, 1, 1]
    tdnn_dilations: [1, 2, 3, 1, 1]
    lin_neurons: !ref <emb_dim>

classifier: !new:custom_model.Classifier
    input_shape: [null, null, !ref <emb_dim>]
    activation: !name:torch.nn.LeakyReLU
    lin_blocks: 1
    lin_neurons: !ref <emb_dim>
    out_neurons: !ref <n_classes>

label_encoder: !new:speechbrain.dataio.encoder.CategoricalEncoder


modules:
    compute_features: !ref <compute_features>
    embedding_model: !ref <embedding_model>
    classifier: !ref <classifier>
    mean_var_norm: !ref <mean_var_norm>

pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    loadables:
        embedding_model: !ref <embedding_model>
        classifier: !ref <classifier>
        label_encoder: !ref <label_encoder>
    paths:
        embedding_model: !ref <pretrained_path>/embedding_model.ckpt
        classifier: !ref <pretrained_path>/classifier.ckpt
        label_encoder: !ref <pretrained_path>/label_encoder.txt
```

(edit anautsch: formatting that uses ``` blocks for better visualisation)
