### ISSUE TITLE
[Bug]: Even when the batch size is 1, CUDA is out of memory. What should I do?

### ISSUE THREAD

**Issue by zuowanbushiwo** [speechbrain/speechbrain#1850]
### Describe the bug

1. I want to train a sepformer model for speech separation, path: speechbrain/recipes/LibriMix/separation/hparams/sepformer-libri2mix.yaml
2. I have 4 RTX3090 graphics cards, each with 24G memory, as shown below:
![image](https://user-images.githubusercontent.com/3354428/220000436-be1d9281-c13e-4ebb-809e-7557db2320ac.png)
3. The training reported the following error:
`RuntimeError: CUDA out of memory. Tried to allocate 212.00 MiB (GPU 0; 23.70 GiB total capacity; 21.03 GiB already allocated; 96.81 MiB free; 22.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

### Expected behaviour

normal training

### To Reproduce

python train.py hparams/sepformer-libri2mix.yaml

**Comment by lucadellalib** [comment]
@zuowanbushiwo gradient checkpointing (https://pytorch.org/docs/stable/checkpoint.html) might help

**Comment by zuowanbushiwo** [comment]
I read some introductions and still don’t know how to use it. Do I need to modify a lot of codes? @lucadellalib

**Comment by lucadellalib** [comment]
@zuowanbushiwo it should be enough to modify lines 82-83 in `train.py` as follows:
```python
# Separation
# mix_w = self.hparams.Encoder(mix)
# est_mask = self.hparams.MaskNet(mix_w)
mix_w = torch.utils.checkpoint.checkpoint(
    self.hparams.Encoder, mix,
)
est_mask = torch.utils.checkpoint.checkpoint(
    self.hparams.MaskNet, mix_w,
)
```
This change was enough for me to run SepFormer on WSJ0-2mix with an 8 GB GPU. You can find a quick tutorial here: https://qywu.github.io/2019/05/22/explore-gradient-checkpointing.html

**Comment by zuowanbushiwo** [comment]
@lucadellalib 
Thank you very much, I can train normally after following your modification.

**Comment by zuowanbushiwo** [comment]
@ycemsubakan @lucadellalib   trian_loss and val_loss seems wrong？
```
epoch: 1, lr: 1.50e-04 - train si-snr: 1.96 - valid si-snr: 8.69e-02
epoch: 2, lr: 1.50e-04 - train si-snr: 3.85e-02 - valid si-snr: -1.75e-01
epoch: 3, lr: 1.50e-04 - train si-snr: -1.57e-01 - valid si-snr: -2.32e-01
epoch: 4, lr: 1.50e-04 - train si-snr: -2.04e-01 - valid si-snr: -2.66e-01
epoch: 5, lr: 1.50e-04 - train si-snr: -2.18e-01 - valid si-snr: -2.82e-01
epoch: 6, lr: 1.50e-04 - train si-snr: -2.29e-01 - valid si-snr: -2.76e-01
epoch: 7, lr: 1.50e-04 - train si-snr: -2.43e-01 - valid si-snr: -2.71e-01
epoch: 8, lr: 1.50e-04 - train si-snr: -2.34e-01 - valid si-snr: -2.61e-01
epoch: 9, lr: 7.50e-05 - train si-snr: -2.51e-01 - valid si-snr: -2.85e-01
epoch: 10, lr: 7.50e-05 - train si-snr: -2.45e-01 - valid si-snr: -2.72e-01
epoch: 11, lr: 7.50e-05 - train si-snr: -2.38e-01 - valid si-snr: -2.80e-01
epoch: 12, lr: 7.50e-05 - train si-snr: -2.40e-01 - valid si-snr: -2.88e-01
epoch: 13, lr: 7.50e-05 - train si-snr: -2.53e-01 - valid si-snr: -2.86e-01
epoch: 14, lr: 7.50e-05 - train si-snr: -2.49e-01 - valid si-snr: -2.77e-01
```
```

# Generated 2023-02-27 from:
# /home/yangjie/speechbrain/recipes/LibriMix/separation/hparams/sepformer-libri2mix.yaml
# yamllint disable
# ################################
# Model: SepFormer for source separation
# https://arxiv.org/abs/2010.13154
# Dataset : Libri2mix
# ################################
#
# Basic parameters
# Seed needs to be set at top of yaml, before objects with parameters are made
#
seed: 1234
__set_seed: !apply:torch.manual_seed [1234]

# Data params

# e.g. '/yourpath/Libri2Mix/train-clean-360/'
# the data folder is needed even if dynamic mixing is applied
data_folder: /data/yangjie/LibriMix/Libri2Mix

# this is the base folder for dynamic mixing
base_folder_dm: /data/yangjie/LibriMix

experiment_name: sepformer-libri2mix
output_folder: results/sepformer-libri2mix/1234
train_log: results/sepformer-libri2mix/1234/train_log.txt
save_folder: results/sepformer-libri2mix/1234/save
train_data: results/sepformer-libri2mix/1234/save/libri2mix_train-360.csv
valid_data: results/sepformer-libri2mix/1234/save/libri2mix_dev.csv
test_data: results/sepformer-libri2mix/1234/save/libri2mix_test.csv
skip_prep: false

ckpt_interval_minutes: 60

# Experiment params
auto_mix_prec: true # Set it to True for mixed precision
test_only: false
num_spks: 2
noprogressbar: false
save_audio: false # Save estimated sources on disk
sample_rate: 8000

# Training parameters
N_epochs: 200
batch_size: 4
lr: 0.00015
clip_grad_norm: 5
loss_upper_lim: 999999  # this is the upper limit for an acceptable loss
# if True, the training sequences are cut to a specified length
limit_training_signal_len: false
# this is the length of sequences if we choose to limit
# the signal length of training sequences
training_signal_len: 32000000

# Set it to True to dynamically create mixtures at training time
dynamic_mixing: false
use_wham_noise: false

# Parameters for data augmentation
use_wavedrop: false
use_speedperturb: true
use_rand_shift: false
min_shift: -8000
max_shift: 8000

speedperturb: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
  perturb_prob: 1.0
  drop_freq_prob: 0.0
  drop_chunk_prob: 0.0
  sample_rate: 8000
  speeds: [95, 100, 105]

wavedrop: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
  perturb_prob: 0.0
  drop_freq_prob: 1.0
  drop_chunk_prob: 1.0
  sample_rate: 8000

# loss thresholding -- this thresholds the training loss
threshold_byloss: true
threshold: -30

# Encoder parameters
N_encoder_out: 256
out_channels: 256
kernel_size: 16
kernel_stride: 8
d_ffn: 1024

# Dataloader options
dataloader_opts:
  batch_size: 4
  num_workers: 4


# Specifying the network
Encoder: &id003 !new:speechbrain.lobes.models.dual_path.Encoder
  kernel_size: 16
  out_channels: 256


SBtfintra: &id001 !new:speechbrain.lobes.models.dual_path.SBTransformerBlock
  num_layers: 8
  d_model: 256
  nhead: 8
  d_ffn: 1024
  dropout: 0
  use_positional_encoding: true
  norm_before: true

SBtfinter: &id002 !new:speechbrain.lobes.models.dual_path.SBTransformerBlock
  num_layers: 8
  d_model: 256
  nhead: 8
  d_ffn: 1024
  dropout: 0
  use_positional_encoding: true
  norm_before: true

MaskNet: &id005 !new:speechbrain.lobes.models.dual_path.Dual_Path_Model

  num_spks: 2
  in_channels: 256
  out_channels: 256
  num_layers: 2
  K: 250
  intra_model: *id001
  inter_model: *id002
  norm: ln
  linear_layer_after_inter_intra: false
  skip_around_intra: true

Decoder: &id004 !new:speechbrain.lobes.models.dual_path.Decoder
  in_channels: 256
  out_channels: 1
  kernel_size: 16
  stride: 8
  bias: false

optimizer: !name:torch.optim.Adam
  lr: 0.00015
  weight_decay: 0

loss: !name:speechbrain.nnet.losses.get_si_snr_with_pitwrapper

lr_scheduler: !new:speechbrain.nnet.schedulers.ReduceLROnPlateau
  factor: 0.5
  patience: 2
  dont_halve_until_epoch: 5

epoch_counter: &id006 !new:speechbrain.utils.epoch_loop.EpochCounter
        # lr_scheduler: !ref <lr_scheduler>

  limit: 200

modules:
  encoder: *id003
  decoder: *id004
  masknet: *id005
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: results/sepformer-libri2mix/1234/save
  recoverables:
    encoder: *id003
    decoder: *id004
    masknet: *id005
    counter: *id006
train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: results/sepformer-libri2mix/1234/train_log.txt

# If you do not want to use the pretrained separator you can simply delete pretrained_separator field.
# pretrained_separator: !new:speechbrain.utils.parameter_transfer.Pretrainer
#     collect_in: !ref <save_folder>
#     loadables:
#         encoder: !ref <Encoder>
#         decoder: !ref <Decoder>
#         masknet: !ref <MaskNet>
#     paths:
#         encoder: speechbrain/sepformer-wsj02mix/encoder.ckpt
#         decoder: speechbrain/sepformer-wsj02mix/decoder.ckpt
#         masknet: speechbrain/sepformer-wsj02mix/masknet.ckpt

```
