### ISSUE TITLE
Upgrading S2SBeamSearcher to 1.0 version yields worse results

### ISSUE THREAD

**Issue by lucasatlalilo** [speechbrain/speechbrain#2631]
### Describe the bug

We have been using Speechbrain to train ASR models for a while. We were using 0.5.16 with a S2STRansformerBeamSearcher based on the recipe from CommonVoice/ASR/transformer with some adaptations to fit our own dataset.
Now we are updating to Speechbrain 1.0 and we updated to continue fitting the recipe (using a ScorerBuilder and CTCScorer), but the evaluation yields far worse results, with a PER of 92% (compared to a previous result of 39%)
So we are trying to understand if this is a bug or a mistake on the implementation on our side.

### Expected behaviour

With the updates that we followed in the recipe we should have exactly the same metrics since nothing else should have changed.

### To Reproduce

Previous yaml definition:

```
test_beam_searcher: !new:speechbrain.decoders.S2STransformerBeamSearch
  modules: [!ref <Transformer>, !ref <seq_lin>, !ref <ctc_lin>]
  bos_index: !ref <label_parameters[bos_index]>
  eos_index: !ref <label_parameters[eos_index]>
  blank_index: !ref <label_parameters[blank_index]>
  min_decode_ratio: !ref <decoding_parameters[min_decode_ratio]>
  max_decode_ratio: !ref <decoding_parameters[max_decode_ratio]>
  beam_size: !ref <decoding_parameters[test_beam_size]>
  ctc_weight: !ref <decoding_parameters[ctc_weight_decode]>
  using_eos_threshold: !ref <decoding_parameters[using_eos_threshold]>
  length_normalization: !ref <decoding_parameters[length_normalization]>
```
  
Updated yaml definition:

```
ctc_scorer: !new:speechbrain.decoders.CTCScorer
  ctc_fc: !ref <ctc_lin>
  blank_index: !ref <label_parameters[blank_index]>
  eos_index: !ref <label_parameters[eos_index]>

scorer: !new:speechbrain.decoders.ScorerBuilder
  full_scorers: [!ref <ctc_scorer>]
  weights:
    ctc: !ref <decoding_parameters[ctc_weight_decode]>

test_beam_searcher: !new:speechbrain.decoders.S2STransformerBeamSearcher
  modules: [!ref <Transformer>, !ref <seq_lin>]
  bos_index: !ref <label_parameters[bos_index]>
  eos_index: !ref <label_parameters[eos_index]>
  min_decode_ratio: !ref <decoding_parameters[min_decode_ratio]>
  max_decode_ratio: !ref <decoding_parameters[max_decode_ratio]>
  beam_size: !ref <decoding_parameters[test_beam_size]>
  using_eos_threshold: !ref <decoding_parameters[using_eos_threshold]>
  length_normalization: !ref <decoding_parameters[length_normalization]>
  scorer : !ref <scorer>
```

### Environment Details

From Speechbrain 0.5.16 to 1.0

### Additional Context

We also tried running it without the CTCScorer, but the issue still persisted and we had a PER higher than expected.

Thanks for your help!
