### ISSUE TITLE
Override sub-element of hparams.yaml using command line args?

### ISSUE THREAD

**Issue by Craya** [speechbrain/speechbrain#2729]
### Describe the bug

It seems not possible to override sub-element parameter of hparams.yaml using command line args.

**Example:**
Let's consider CommonVoice Wav2Vec2 recipe, hparam.yaml file contains:
```
[...]
# Outputs
output_neurons: 76  # BPE size, index(blank/eos/bos) = 0
[...]
# Decoding parameters
test_beam_search:
    blank_index: !ref <blank_index>
    beam_size: 100
    beam_prune_logp: -12.0
    token_prune_min_logp: -1.2
    prune_history: True
    topk: 1
    alpha: 1.0
    beta: 0.5
    # To use n-gram LM for decoding, follow steps in README.md.
    # kenlm_model_path: none
[...]
```
Is is possible to override `output_neurons` via command line : `./train_with_wav2vec.py hparams/train_en_with_wav2vec.yaml --output_neurons=250`
However, it seems not possible to override parameter like `prune_history` or `kenlm_model_path` as they are sub-parameters of the `test_beam_search` entity

### Expected behaviour

To be able to override any element of hparam.yaml using command line.

### To Reproduce

```
./train_with_wav2vec.py hparams/train_en_with_wav2vec.yaml --kenlm_model_path='/data/lm/lm_base.arpa'
```

### Relevant Log Output

```shell
KeyError: "Override 'kenlm_model_path:/data/lm/lm_base.arpa' not found in: ['seed', '__set_seed', 'output_folder', 'test_wer_file', 'save_folder', 'train_log', 'wav2vec2_hub', 'wav2vec2_folder', 'data_folder', 'train_tsv_file', 'dev_tsv_file', 'test_tsv_file', 'accented_letters', 'language', 'train_csv', 'valid_csv', 'test_csv', 'skip_prep', 'avoid_if_longer_than', 'number_of_epochs', 'lr', 'lr_wav2vec', 'sorting', 'precision', 'sample_rate', 'ckpt_interval_minutes', 'dynamic_batching', 'batch_size', 'test_batch_size', 'dataloader_options', 'test_dataloader_options', 'token_type', 'character_coverage', 'wav2vec_output_dim', 'dnn_neurons', 'freeze_wav2vec', 'freeze_feature_extractor', 'dropout', 'warmup_steps', 'output_neurons', 'blank_index', 'bos_index', 'eos_index', 'test_beam_search', 'epoch_counter', 'speed_perturb', 'drop_freq', 'drop_chunk', 'wav_augment', 'enc', 'wav2vec2', 'ctc_lin', 'log_softmax', 'ctc_cost', 'modules', 'model', 'model_opt_class', 'wav2vec_opt_class', 'lr_annealing_model', 'lr_annealing_wav2vec', 'checkpointer', 'train_logger', 'error_rate_computer', 'cer_computer']"
```
