### ISSUE TITLE
[BUG] SpeechBrain version 1.0.2 broke local fetching

### ISSUE THREAD

**Issue by daniel-tsiang** [speechbrain/speechbrain#2817]
### Describe the bug

Version 1.0.2 of speechbrain caused problems when attempting to load the model files locally

I managed to recreate the error locally:
```
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
```

The `hyperparams.yaml` file was fetched correctly locally. But inside that file, it contains `pretrained_path: speechbrain/spkrec-ecapa-voxceleb`. It always tries to fetch model files (e.g. `classifier.ckpt`) from huggingface under `speechbrain/spkrec-ecapa-voxceleb` no matter what config was set. We do not want to pull model files directly from huggingface, due to security and versioning concerns. The above error was triggered when the code was run from inside Kubernetes, which was configured to not allow access to the outside public internet.

So I think 1.0.2 has simply broken local fetching. In version 1.0.1, it uses the local model files correctly.

### Expected behaviour

When setting the following:

```python
from speechbrain.inference.speaker import SpeakerRecognition as _SpeakerRecognition

model = SpeakerRecognition.from_hparams(
            source=source, local_strategy=LocalStrategy.COPY_SKIP_CACHE, **kwargs
        )
```

I would expect it to fetch model files from the local system, and not from huggingface remotely.

### To Reproduce

hyperparams.yaml
```yaml
# ############################################################################
# Model: ECAPA big for Speaker verification
# ############################################################################

# Feature parameters
n_mels: 80

# Pretrain folder (HuggingFace)
pretrained_path: speechbrain/spkrec-ecapa-voxceleb

# Output parameters
out_n_neurons: 7205

# Model params
compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: !ref <n_mels>

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False

embedding_model: !new:speechbrain.lobes.models.ECAPA_TDNN.ECAPA_TDNN
    input_size: !ref <n_mels>
    channels: [1024, 1024, 1024, 1024, 3072]
    kernel_sizes: [5, 3, 3, 3, 1]
    dilations: [1, 2, 3, 4, 1]
    attention_channels: 128
    lin_neurons: 192

classifier: !new:speechbrain.lobes.models.ECAPA_TDNN.Classifier
    input_size: 192
    out_neurons: !ref <out_n_neurons>

mean_var_norm_emb: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    std_norm: False

modules:
    compute_features: !ref <compute_features>
    mean_var_norm: !ref <mean_var_norm>
    embedding_model: !ref <embedding_model>
    mean_var_norm_emb: !ref <mean_var_norm_emb>
    classifier: !ref <classifier>
        
label_encoder: !new:speechbrain.dataio.encoder.CategoricalEncoder

        
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    loadables:
        embedding_model: !ref <embedding_model>
        mean_var_norm_emb: !ref <mean_var_norm_emb>
        classifier: !ref <classifier>
        label_encoder: !ref <label_encoder>
    paths:
        embedding_model: !ref <pretrained_path>/embedding_model.ckpt
        mean_var_norm_emb: !ref <pretrained_path>/mean_var_norm_emb.ckpt
        classifier: !ref <pretrained_path>/classifier.ckpt
        label_encoder: !ref <pretrained_path>/label_encoder.txt
```
---

Python code to load local model files, where source is the path to `spkrec-ecapa-voxceleb` i.e. the directory containing `hyperparams.yaml`
```python
from speechbrain.inference.speaker import SpeakerRecognition as _SpeakerRecognition

model = SpeakerRecognition.from_hparams(
            source=source, local_strategy=LocalStrategy.COPY_SKIP_CACHE, **kwargs
        )
```

---

Local directory structure:
<img width="282" alt="Image" src="https://github.com/user-attachments/assets/06aa24b3-19f5-49f2-9150-20dcc41a0568" />

### Environment Details

SpeechBrain version: 1.0.2
Python version: 3.12

### Relevant Log Output

```shell
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
```
