### ISSUE TITLE
LM's yaml of Speech Recognition From Scratch is wrong

### ISSUE THREAD

**Issue by dugudongfangshuo** [speechbrain/speechbrain#720]
RNNLM.yaml
`tokenizer: !new:sentencepiece.SentencePieceProcessor`
tran.py
`tokenizer = hparams["tokenizer"]`

this can't use pre train model to tokenizer model

**Comment by TParcollet** [comment]
Hey hi, 

Not sure to understand properly.

**Comment by dugudongfangshuo** [comment]
in this
[Speech Recognition From Scratch](https://colab.research.google.com/drive/1aFgzrUv3udM_gNJNUoLaHIm78QHtxdIz?usp=sharing#scrollTo=beagAGw5t5bK)
use this `tokenizer: !new:sentencepiece.SentencePieceProcessor` can't tokenizer the words  
can you understand?

**Comment by TParcollet** [comment]
Not really, 

This only say that the YAML variable tokenizer is of type sentencepiece.SentencePieceProcessor

Then the tokenizer is loaded in the Pretrainer:
```yaml
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
   collect_in: !ref <save_folder>
   loadables:
      lm: !ref <lm_model>
      tokenizer: !ref <tokenizer>
   paths:
      lm: !ref <pretrained_lm_tokenizer_path>/lm.ckpt
      tokenizer: !ref <pretrained_lm_tokenizer_path>/tokenizer.ckpt
```

**Comment by dugudongfangshuo** [comment]
train.py  is in the templates/speech_recognition/LM/
But  In the train.py  I do not find where to use  pretrainer  , can you tell me the Pretrainer how to work in the train

**Comment by TParcollet** [comment]
Okay,

So if you are using the templates you must have seen that you need to:
1. Train a tokenizer
2. Train the LM
3. Train the AM

If you are at step 2. it means that you already did one. If you look at the LM yaml, you will see:

```yaml
# Pretrain the tokenizer
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    loadables:
        tokenizer: !ref <tokenizer>
    paths:
        tokenizer: !ref <tokenizer_file>
```

In this very same yaml you will find a variable named `tokenizer_file` that must contain the path to the tokenizer you trained on step 1 :-) The pretrainer will then do the link automatically. Do not hesitate to check our tutorials specifically done on this topic.
